# Generated by Django 4.1.7 on 2023-02-16 11:56

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='пароль')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='последний логин')),
                ('is_superuser', models.BooleanField(default=False, help_text='Обозначает, что этот пользователь имеет все разрешения без их явного назначения.', verbose_name='админ статус')),
                ('username', models.CharField(error_messages={'unique': 'Юзер с таким никнеймом уже существует.'}, help_text='Требуется. Не более 150 символов. Только буквы, цифры и @/./+/-/_.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Никнейм')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Фамилия')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail адрес')),
                ('is_staff', models.BooleanField(default=False, help_text='Указывает, может ли пользователь войти на этот сайт администратора.', verbose_name='стафф статус')),
                ('is_active', models.BooleanField(default=True, help_text='Указывает, следует ли считать этого пользователя активным. Снимите этот флажок вместо удаления учетных записей.', verbose_name='активно')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата входа')),
                ('groups', models.ManyToManyField(blank=True, help_text='Группы, к которым принадлежит данный пользователь. Пользователь получает все разрешения, предоставленные каждой из его групп.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='группы')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Конкретные права для пользователя.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='права пользователя')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
